version: 2.1
orbs:
  newman: postman/newman@5.3.2

jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./collection.json